services:
  - type: web
    name: student-application-backend
    env: python
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: MONGODB_URI
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: UPLOAD_FOLDER
        value: uploads
      - key: FLASK_DEBUG
        value: False